---
- name: COL TO APP [1] to expansion-client
  wait_for:
    host: "{{ groups['expansion_client'][0] }}"
    port: "{{ port }}"
    timeout: 1
    state: started
  check_mode: no
  with_items:
    - "4007"
  loop_control:
    loop_var: port  
  register: wait_result 
  ignore_errors: yes


- name: COL TO APP [2] jdown to puppet-master
  wait_for:
    host: "{{ groups['puppet_master'][0] }}"
    port: "{{ port }}"
    timeout: 1
    state: started
  check_mode: no
  with_items:
    - "4045"
  loop_control:
    loop_var: port  
  register: wait_result 
  ignore_errors: yes


- name: COL TO APP [3] to topic-collector
  wait_for:
    host: "{{ groups['topic_collector'][0] }}"
    port: "{{ port }}"
    timeout: 1
    state: started
  check_mode: no
  with_items:
    - "3861"
  loop_control:
    loop_var: port  
  register: wait_result 
  ignore_errors: yes


- name: COL TO APP [4] to collection-client
  wait_for:
    host: "{{ groups['collection_client'][0] }}"
    port: "{{ port }}"
    timeout: 1
    state: started
  check_mode: no
  with_items:
    - "3993"
  loop_control:
    loop_var: port  
  register: wait_result 
  ignore_errors: yes


- name: COL TO APP [5] to social-data-service
  wait_for:
    host: "{{ groups['social_data_service'][0] }}"
    port: "{{ port }}"
    timeout: 1
    state: started
  check_mode: no
  with_items:
    - "4020"
  loop_control:
    loop_var: port  
  register: wait_result 
  ignore_errors: yes


