
- name: start msg
  debug:
    msg: echo "connectivity-check"


- name: ALL-2-ADMIN
  include_tasks: "{{ item }}"
  loop:
    - all_2_adm1.yml
    - all_2_adm2.yml
    - adm_2_app.yml
    - adm_2_col.yml
    - web_2_app.yml
    - col_2_app.yml
