---
- name: WEB TO APP [1]jback to users-management
  wait_for:
    host: "{{ groups['users_management'][0] }}"
    port: "{{ port }}"
    timeout: 1
    state: started
  check_mode: no
  with_items:
    - "4001"
  loop_control:
    loop_var: port  
  register: wait_result 
  ignore_errors: yes

