---
- name: Check FW between tiers
  gather_facts: false
  hosts: voyager_servers

  vars:
    ansible_ssh_user: deploy
    ansible_port: 3832

  tasks:
    - name: connectivity check
      include_role:
        name: connectivity
