---
all:
  children:
    admin_client:
      hosts:
        10.56.12.11: {}
    ansible:
      hosts:
        10.56.8.11: {}
    cassandra:
      hosts:
        10.56.10.11: {}
        10.56.10.12: {}
        10.56.10.13: {}
        10.56.10.14: {}
    cluster:
      hosts: {}
    collection_client:
      hosts:
        10.56.9.15: {}
    collector_topology:
      hosts:
        10.56.11.11: {}
    common:
      hosts: {}
    configuration_service:
      hosts:
        10.56.8.12: {}
    discovery_service:
      hosts:
        10.56.8.12: {}
    expansion_client:
      hosts:
        10.56.9.13: {}
    flow_manager:
      hosts:
        10.56.11.11: {}
    jback:
      hosts:
        10.56.12.11: {}
    jclient:
      hosts:
        10.56.12.11: {}
    jdown:
      hosts:
        10.56.11.11: {}
    jenkins:
      hosts:
        10.56.8.11: {}
    jfile:
      hosts:
        10.56.9.11: {}
    jgate:
      hosts:
        10.56.11.11: {}
    jhtop:
      hosts:
        10.56.9.11: {}
    jlimiter:
      hosts:
        10.56.11.11: {}
    jscheduler:
      hosts:
        10.56.9.12: {}
    jtool:
      hosts:
        10.56.10.11: {}
    mariadb:
      hosts:
        10.56.10.14: {}
    mnw2vec:
      hosts:
        10.56.9.14: {}
    mongodb:
      hosts:
        10.56.10.11: {}
        10.56.10.12: {}
        10.56.10.13: {}
    msearch_solr:
      hosts:
        10.56.9.14: {}
    mstory:
      hosts:
        10.56.9.14: {}
    payment_service:
      hosts:
        10.56.9.12: {}
    policy_management:
      hosts:
        10.56.9.12: {}
    postgres:
      hosts:
        10.56.10.14: {}
    puppet_master:
      hosts:
        10.56.9.13: {}
    puppet_worker:
      hosts:
        10.56.11.13: {}
    query_director:
      hosts:
        10.56.9.12: {}
    query_manager:
      hosts:
        10.56.9.12: {}
    queue_dispatcher:
      hosts:
        10.56.11.11: {}
    rabbitmq:
      hosts:
        10.56.11.11: {}
    redis:
      hosts:
        10.56.10.14: {}
    report_service:
      hosts:
        10.56.9.13: {}
    secure:
      hosts: {}
    sensu_master:
      hosts:
        10.56.8.11: {}
    social_data_service:
      hosts:
        10.56.9.15: {}
    solr:
      hosts:
        10.56.10.18: {}
        10.56.10.19: {}
        10.56.10.20: {}
        10.56.10.21: {}
    squid:
      hosts:
        10.56.8.11: {}
    storm_nimbus:
      hosts:
        10.56.11.11: {}
    storm_supervisor:
      hosts:
        10.56.11.12: {}
    telegram_service:
      hosts:
        10.56.11.13: {}
    topic_collector:
      hosts:
        10.56.9.13: {}
    topic_service:
      hosts:
        10.56.9.13: {}
    users_management:
      hosts:
        10.56.9.12: {}
    voyager_servers:
      hosts:
        10.56.10.11: {}
        10.56.10.12: {}
        10.56.10.13: {}
        10.56.10.14: {}
        10.56.10.15: {}
        10.56.10.16: {}
        10.56.10.17: {}
        10.56.10.18: {}
        10.56.10.19: {}
        10.56.10.20: {}
        10.56.10.21: {}
        10.56.11.11: {}
        10.56.11.12: {}
        10.56.11.13: {}
        10.56.12.11: {}
        10.56.8.11: {}
        10.56.8.12: {}
        10.56.9.11: {}
        10.56.9.12: {}
        10.56.9.13: {}
        10.56.9.14: {}
        10.56.9.15: {}
      vars:
        alias: va-czr
        env: onprem
        platform: vmware
        project: va
    zookeeper:
      hosts:
        10.56.10.15: {}
        10.56.10.16: {}
        10.56.10.17: {}
  hosts:
    10.56.10.11:
      '#': '11'
      Name: va-czr-db-1
      component: cassandra,jtool,mongodb
      ip address: 10.56.10.11
      memory gb: '8'
      name: va-czr-db-1
      private_ip: 10.56.10.11
      storage gb: 100gb hdd for root partition 2nd 200gb hdd for db 3rd 200gb hdd
      tier: db
      vcpu: '4'
    10.56.10.12:
      '#': '12'
      Name: va-czr-db-2
      component: cassandra,mongodb
      ip address: 10.56.10.12
      memory gb: '8'
      name: va-czr-db-2
      private_ip: 10.56.10.12
      storage gb: 100gb hdd for root partition 2nd 200gb hdd for db 3rd 200gb hdd
      tier: db
      vcpu: '4'
    10.56.10.13:
      '#': '13'
      Name: va-czr-db-3
      component: cassandra,mongodb
      ip address: 10.56.10.13
      memory gb: '8'
      name: va-czr-db-3
      private_ip: 10.56.10.13
      storage gb: 100gb hdd for root partition 2nd 200gb hdd for db 3rd 200gb hdd
      tier: db
      vcpu: '4'
    10.56.10.14:
      '#': '14'
      Name: va-czr-db-4
      component: cassandra,mariadb, redis, postgres
      ip address: 10.56.10.14
      memory gb: '8'
      name: va-czr-db-4
      private_ip: 10.56.10.14
      storage gb: 100gb hdd for root partition 2nd 200gb hdd for db 3rd 200gb hdd
      tier: db
      vcpu: '4'
    10.56.10.15:
      '#': '15'
      Name: va-czr-db-5
      component: zookeeper
      ip address: 10.56.10.15
      memory gb: '4'
      name: va-czr-db-5
      private_ip: 10.56.10.15
      storage gb: 100gb hdd for root partition
      tier: db
      vcpu: '2'
    10.56.10.16:
      '#': '16'
      Name: va-czr-db-6
      component: zookeeper
      ip address: 10.56.10.16
      memory gb: '4'
      name: va-czr-db-6
      private_ip: 10.56.10.16
      storage gb: 100gb hdd for root partition
      tier: db
      vcpu: '2'
    10.56.10.17:
      '#': '17'
      Name: va-czr-db-7
      component: zookeeper
      ip address: 10.56.10.17
      memory gb: '4'
      name: va-czr-db-7
      private_ip: 10.56.10.17
      storage gb: 100gb hdd for root partition
      tier: db
      vcpu: '2'
    10.56.10.18:
      '#': '18'
      Name: va-czr-db-8
      component: solr
      ip address: 10.56.10.18
      memory gb: '16'
      name: va-czr-db-8
      private_ip: 10.56.10.18
      storage gb: 100gb hdd for root partition 2nd 200gb hdd for db
      tier: db
      vcpu: '4'
    10.56.10.19:
      '#': '19'
      Name: va-czr-db-9
      component: solr
      ip address: 10.56.10.19
      memory gb: '16'
      name: va-czr-db-9
      private_ip: 10.56.10.19
      storage gb: 100gb hdd for root partition 2nd 200gb hdd for db
      tier: db
      vcpu: '4'
    10.56.10.20:
      '#': '20'
      Name: va-czr-db-10
      component: solr
      ip address: 10.56.10.20
      memory gb: '16'
      name: va-czr-db-10
      private_ip: 10.56.10.20
      storage gb: 100gb hdd for root partition 2nd 200gb hdd for db
      tier: db
      vcpu: '4'
    10.56.10.21:
      '#': '21'
      Name: va-czr-db-11
      component: solr
      ip address: 10.56.10.21
      memory gb: '16'
      name: va-czr-db-11
      private_ip: 10.56.10.21
      storage gb: 100gb hdd for root partition 2nd 200gb hdd for db
      tier: db
      vcpu: '4'
    10.56.11.11:
      '#': '8'
      Name: va-czr-col-1
      component: storm-nimbus,collector-topology,flow-manager,jdown,jgate,jlimiter,queue-dispatcher,rabbitmq
      ip address: 10.56.11.11
      memory gb: '16'
      name: va-czr-col-1
      private_ip: 10.56.11.11
      storage gb: 100gb hdd for root partition
      tier: collection
      vcpu: '4'
    10.56.11.12:
      '#': '9'
      Name: va-czr-col-2
      component: storm-supervisor
      ip address: 10.56.11.12
      memory gb: '16'
      name: va-czr-col-2
      private_ip: 10.56.11.12
      storage gb: 100gb hdd for root partition
      tier: collection
      vcpu: '4'
    10.56.11.13:
      '#': '10'
      Name: va-czr-col-3
      component: telegram-service,puppet-worker
      ip address: 10.56.11.13
      memory gb: '8'
      name: va-czr-col-3
      private_ip: 10.56.11.13
      storage gb: 100gb hdd for root partition
      tier: collection
      vcpu: '4'
    10.56.12.11:
      '#': '22'
      Name: va-czr-web-1
      component: jback,jclient,admin-client
      ip address: 10.56.12.11
      memory gb: '8'
      name: va-czr-web-1
      private_ip: 10.56.12.11
      storage gb: 100gb hdd for root partition
      tier: web
      vcpu: '4'
    10.56.8.11:
      '#': '1'
      Name: va-czr-adm-1
      component: jenkins,ansible,sensu-master, squid
      ip address: 10.56.8.11
      memory gb: '8'
      name: va-czr-adm-1
      private_ip: 10.56.8.11
      storage gb: 100gb hdd for root partition
      tier: admin
      vcpu: '4'
    10.56.8.12:
      '#': '2'
      Name: va-czr-adm-2
      component: configuration-service,discovery-service
      ip address: 10.56.8.12
      memory gb: '4'
      name: va-czr-adm-2
      private_ip: 10.56.8.12
      storage gb: 100gb hdd for root partition
      tier: admin
      vcpu: '2'
    10.56.9.11:
      '#': '3'
      Name: va-czr-app-1
      component: jfile, jhtop
      ip address: 10.56.9.11
      memory gb: '16'
      name: va-czr-app-1
      private_ip: 10.56.9.11
      storage gb: 100gb hdd for root partition 2nd 500gb hdd attached
      tier: app
      vcpu: '4'
    10.56.9.12:
      '#': '4'
      Name: va-czr-app-2
      component: jscheduler,payment-service,query-manager,query-director,users-management,policy-management
      ip address: 10.56.9.12
      memory gb: '8'
      name: va-czr-app-2
      private_ip: 10.56.9.12
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '2'
    10.56.9.13:
      '#': '5'
      Name: va-czr-app-3
      component: expansion-client,topic-collector,topic-service,report-service,puppet-master
      ip address: 10.56.9.13
      memory gb: '8'
      name: va-czr-app-3
      private_ip: 10.56.9.13
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '4'
    10.56.9.14:
      '#': '6'
      Name: va-czr-app-4
      component: mnw2vec,mstory,msearch-solr
      ip address: 10.56.9.14
      memory gb: '16'
      name: va-czr-app-4
      private_ip: 10.56.9.14
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '8'
    10.56.9.15:
      '#': '7'
      Name: va-czr-app-5
      component: collection-client,social-data-service
      ip address: 10.56.9.15
      memory gb: '8'
      name: va-czr-app-5
      private_ip: 10.56.9.15
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '4'
